In [1]:
import numpy as np
list1 = [1,2,3,4,5,6]

oneDimExample = np.array(list1)

In [3]:
oneDimExample.ndim

1

In [4]:
oneDimExample.shape

(6,)

In [5]:
twoDimExample = np.array([[1,2,3],
                         [4,5,6],
                         [7,8,9]])

In [8]:
type(twoDimExample)

numpy.ndarray

In [9]:
array1 = np.array([4,2,5,2,78,9,900,234,567,2,1])
array1.max() #max value in the array

np.int64(900)

In [11]:
k = array1.argmax() #index location of the max value

In [18]:
int(array1.min())

1

In [27]:
data = np.random.randint(1,100,9)
data

array([87, 97, 50, 11, 20, 11, 55, 67, 40], dtype=int32)

In [28]:
data = data.reshape(3,3)

In [30]:
data.reshape(9,1)

array([[87],
       [97],
       [50],
       [11],
       [20],
       [11],
       [55],
       [67],
       [40]], dtype=int32)

In [31]:
data.ndim

2

In [32]:
data.ravel()

array([87, 97, 50, 11, 20, 11, 55, 67, 40], dtype=int32)

In [33]:
data.ravel().ndim

1

In [40]:
data1 = np.random.randint(1,100,16)
data1

array([70, 26, 96, 67, 20, 63, 50, 53, 11, 54, 38, 13, 87, 35, 42, 22],
      dtype=int32)

In [47]:
data = data1.astype(np.float64)

In [49]:
data = data.reshape(4,4)

In [56]:
data

array([[70., 26., 96., 67.],
       [20., 63., 50., 53.],
       [11., 54., 38., 13.],
       [87., 35., 42., 22.]])

In [59]:
data[0:2,1:4]

array([[26., 96., 67.],
       [63., 50., 53.]])